### ISSUE TITLE
Bug: Fix Port Binding for all sidecars to expose metrics 

### ISSUE THREAD

**Issue by JayGhiya** [unoplat/unoplat-service-mesh#76]
In addition to updating your Consul environment, you will also configure the Envoy proxy sidecars in your service mesh to expose a Prometheus metrics endpoint. This allows Prometheus to scrape metrics from the Envoy sidecar proxies.

The ProxyDefaults configuration entry lets you configure global defaults across all services for Consul service mesh proxy configurations. The proxy/proxy-defaults.yaml file configures envoy_prometheus_bind_addr to expose a Prometheus metrics endpoint.
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    envoy_prometheus_bind_addr: '0.0.0.0:20200
```
